# примеры API-запросов

@baseUrl = http://127.0.0.1:8000/api

# получение объявлений
GET {{baseUrl}}/adv/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/adv/
Content-Type: application/json
Authorization: Token 68b9252e52d697fb253a38d465c48553ab28e16f

{
  "title": "Шкаф IKEA6",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/adv/1/
Content-Type: application/json
Authorization: Token 68b9252e52d697fb253a38d465c48553ab28e16f

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/adv/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/adv/?created_at_before=2024-08-09
Content-Type: application/json
