# Generated by Django 5.0.2 on 2024-08-08 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_alter_advertisement_options_alter_advertisement_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='creator',
            new_name='user',
        ),
    ]
