# Generated by Django 5.0.2 on 2024-08-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_rename_creator_advertisement_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='user',
            new_name='creator',
        ),
    ]
