# Generated by Django 5.0.6 on 2024-06-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('release_date', models.DateField(default='2024-06-06')),
                ('lte_exists', models.BooleanField(default=0)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Phone',
            },
        ),
    ]
